import type { PrismaClient } from "@prisma/client";

const IMG = {
  audio: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800",
  watch: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800",
  laptop: "https://images.unsplash.com/photo-1496181133176-c407dc4b2d4f?w=800",
  sneakers: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800",
  denim: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800",
  speaker: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800",
  gaming: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800",
  controller: "https://images.unsplash.com/photo-1598301298708-575eee5c0858?w=800",
  keyboard: "https://images.unsplash.com/photo-1592840492550-473bfdd6a771?w=800",
  headset: "https://images.unsplash.com/photo-1618366712010-f4ae9a51a6d0?w=800",
  console: "https://images.unsplash.com/photo-1486401899862-0a3f3d5b1a3e?w=800",
  switchImg: "https://images.unsplash.com/photo-1578303512597-81e6cc38b8d2?w=800",
  mouse: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800",
  monitor: "https://images.unsplash.com/photo-1527443224754-1219d9a6d2b7?w=800",
  chair: "https://images.unsplash.com/photo-1598550476439-6847785fcea6?w=800",
  dress2: "https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=800",
  chinos: "https://images.unsplash.com/photo-1473966962640-6e420c6f6b0b?w=800",
  bag: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800",
  earrings: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800",
  boots: "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800",
  heels: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800",
  hoodie: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800",
  blazer: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800",
  sofa: "https://images.unsplash.com/photo-1555041469-a586c61e9bc7?w=800",
  lamp: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800",
  cookware: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800",
  yoga: "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=800",
  tent: "https://images.unsplash.com/photo-1478131143081-80f7f84b404e?w=800",
  dumbbell: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800",
  serum: "https://images.unsplash.com/photo-1620916564558-827411649d0b?w=800",
  lipstick: "https://images.unsplash.com/photo-1586495778184-0e7d2b0e0b0e?w=800",
  lipstick2: "https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=800",
  phone: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800",
  hub: "https://images.unsplash.com/photo-1625948515291-696cec8d5597?w=800",
  earbuds: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800",
  books: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800",
  toys: "https://images.unsplash.com/photo-1558060370-aba9b14b4237?w=800",
  sunglasses: "https://images.unsplash.com/photo-1572635196233-224f07350c8c?w=800",
};

type ProductSeed = {
  name: string;
  slug: string;
  description: string;
  price: number;
  comparePrice?: number;
  brand: string;
  stock: number;
  categorySlug: string;
  vendorKey: "tech" | "fashion" | "gaming" | "home";
  isFeatured?: boolean;
  rating?: number;
  reviewCount?: number;
  location?: string;
  image: string;
};

export const EXTRA_PRODUCTS: ProductSeed[] = [
  // Gaming
  {
    name: "DualSense Wireless Controller",
    slug: "dualsense-wireless-controller",
    description: "Official-style wireless controller with adaptive triggers and haptic feedback.",
    price: 69.99,
    comparePrice: 79.99,
    brand: "GameZone",
    stock: 85,
    categorySlug: "gaming-accessories",
    vendorKey: "gaming",
    isFeatured: true,
    rating: 4.7,
    reviewCount: 421,
    location: "Seattle, USA",
    image: IMG.controller,
  },
  {
    name: "RGB Mechanical Gaming Keyboard",
    slug: "rgb-mechanical-gaming-keyboard",
    description: "Hot-swappable switches, per-key RGB, and aluminum frame for serious gamers.",
    price: 119.99,
    comparePrice: 149.99,
    brand: "GameZone",
    stock: 60,
    categorySlug: "gaming-accessories",
    vendorKey: "gaming",
    isFeatured: true,
    rating: 4.6,
    reviewCount: 198,
    location: "Seattle, USA",
    image: IMG.keyboard,
  },
  {
    name: "Pro Gaming Headset 7.1",
    slug: "pro-gaming-headset-7-1",
    description: "Surround sound, detachable mic, and memory foam ear cushions.",
    price: 89.99,
    brand: "GameZone",
    stock: 110,
    categorySlug: "gaming-accessories",
    vendorKey: "gaming",
    rating: 4.5,
    reviewCount: 267,
    location: "Austin, USA",
    image: IMG.headset,
  },
  {
    name: "Next-Gen Gaming Console",
    slug: "next-gen-gaming-console",
    description: "4K gaming, ray tracing, 1TB SSD, includes one wireless controller.",
    price: 499.99,
    brand: "GameZone",
    stock: 18,
    categorySlug: "gaming-consoles",
    vendorKey: "gaming",
    isFeatured: true,
    rating: 4.9,
    reviewCount: 89,
    location: "Seattle, USA",
    image: IMG.console,
  },
  {
    name: "Handheld Gaming System OLED",
    slug: "handheld-gaming-system-oled",
    description: "Vibrant 7-inch OLED screen, 64GB storage, plays at home or on the go.",
    price: 349.99,
    brand: "GameZone",
    stock: 32,
    categorySlug: "gaming-consoles",
    vendorKey: "gaming",
    rating: 4.8,
    reviewCount: 156,
    location: "Portland, USA",
    image: IMG.switchImg,
  },
  {
    name: "Precision Gaming Mouse 16000 DPI",
    slug: "precision-gaming-mouse",
    description: "Ultra-light wireless mouse with programmable buttons and 16000 DPI sensor.",
    price: 79.99,
    comparePrice: 99.99,
    brand: "GameZone",
    stock: 95,
    categorySlug: "gaming-accessories",
    vendorKey: "gaming",
    rating: 4.4,
    reviewCount: 334,
    location: "Austin, USA",
    image: IMG.mouse,
  },
  {
    name: 'Open World RPG — PC Edition',
    slug: "open-world-rpg-pc-edition",
    description: "Award-winning RPG with massive open world. Digital download code included.",
    price: 59.99,
    brand: "GameZone",
    stock: 500,
    categorySlug: "video-games",
    vendorKey: "gaming",
    rating: 4.9,
    reviewCount: 1204,
    location: "Digital",
    image: IMG.gaming,
  },
  {
    name: "Sports Simulator 2025",
    slug: "sports-simulator-2025",
    description: "Latest season rosters, online modes, and career mode for football fans.",
    price: 69.99,
    brand: "GameZone",
    stock: 400,
    categorySlug: "video-games",
    vendorKey: "gaming",
    rating: 4.2,
    reviewCount: 445,
    location: "Digital",
    image: IMG.gaming,
  },
  {
    name: "Ergonomic Racing Gaming Chair",
    slug: "ergonomic-racing-gaming-chair",
    description: "Reclining back, lumbar support, and 4D armrests for marathon sessions.",
    price: 299.99,
    comparePrice: 399.99,
    brand: "GameZone",
    stock: 28,
    categorySlug: "gaming-accessories",
    vendorKey: "gaming",
    isFeatured: true,
    rating: 4.3,
    reviewCount: 112,
    location: "Chicago, USA",
    image: IMG.chair,
  },
  {
    name: '27" 165Hz Gaming Monitor',
    slug: "27-inch-165hz-gaming-monitor",
    description: "QHD IPS panel, 1ms response, G-Sync compatible, height adjustable stand.",
    price: 329.99,
    comparePrice: 399.99,
    brand: "GameZone",
    stock: 22,
    categorySlug: "pc-gaming",
    vendorKey: "gaming",
    isFeatured: true,
    rating: 4.6,
    reviewCount: 78,
    location: "Seattle, USA",
    image: IMG.monitor,
  },
  // Fashion
  {
    name: "Women's Summer Floral Midi Dress",
    slug: "womens-summer-floral-midi-dress",
    description: "Lightweight breathable fabric, flattering A-line cut, perfect for warm days.",
    price: 54.99,
    comparePrice: 79.99,
    brand: "Style Avenue",
    stock: 70,
    categorySlug: "women",
    vendorKey: "fashion",
    isFeatured: true,
    rating: 4.5,
    reviewCount: 89,
    location: "Los Angeles, USA",
    image: IMG.dress2,
  },
  {
    name: "Men's Slim Fit Chino Pants",
    slug: "mens-slim-fit-chino-pants",
    description: "Stretch cotton blend, modern taper, available in classic neutrals.",
    price: 49.99,
    brand: "Style Avenue",
    stock: 90,
    categorySlug: "men",
    vendorKey: "fashion",
    rating: 4.3,
    reviewCount: 156,
    location: "New York, USA",
    image: IMG.chinos,
  },
  {
    name: "Leather Crossbody Handbag",
    slug: "leather-crossbody-handbag",
    description: "Genuine leather, adjustable strap, multiple interior pockets.",
    price: 119.99,
    comparePrice: 159.99,
    brand: "Style Avenue",
    stock: 40,
    categorySlug: "fashion-accessories",
    vendorKey: "fashion",
    isFeatured: true,
    rating: 4.6,
    reviewCount: 67,
    location: "Miami, USA",
    image: IMG.bag,
  },
  {
    name: "Gold-Tone Hoop Earrings Set",
    slug: "gold-tone-hoop-earrings-set",
    description: "Set of 3 sizes, hypoallergenic posts, everyday elegance.",
    price: 24.99,
    brand: "Style Avenue",
    stock: 150,
    categorySlug: "fashion-accessories",
    vendorKey: "fashion",
    rating: 4.4,
    reviewCount: 203,
    location: "Los Angeles, USA",
    image: IMG.earrings,
  },
  {
    name: "Men's Chelsea Boots",
    slug: "mens-chelsea-boots",
    description: "Slip-on design, durable sole, polished finish for smart casual looks.",
    price: 139.99,
    comparePrice: 179.99,
    brand: "Style Avenue",
    stock: 35,
    categorySlug: "fashion-shoes",
    vendorKey: "fashion",
    rating: 4.5,
    reviewCount: 44,
    location: "Chicago, USA",
    image: IMG.boots,
  },
  {
    name: "Women's Classic High Heels",
    slug: "womens-classic-high-heels",
    description: "4-inch heel, cushioned insole, timeless pointed toe silhouette.",
    price: 89.99,
    brand: "Style Avenue",
    stock: 48,
    categorySlug: "fashion-shoes",
    vendorKey: "fashion",
    rating: 4.2,
    reviewCount: 91,
    location: "New York, USA",
    image: IMG.heels,
  },
  {
    name: "Premium Cotton Oversized Hoodie",
    slug: "premium-cotton-oversized-hoodie",
    description: "Unisex fit, brushed fleece interior, kangaroo pocket.",
    price: 44.99,
    brand: "Style Avenue",
    stock: 120,
    categorySlug: "women",
    vendorKey: "fashion",
    rating: 4.7,
    reviewCount: 312,
    location: "Portland, USA",
    image: IMG.hoodie,
  },
  {
    name: "Men's Tailored Blazer",
    slug: "mens-tailored-blazer",
    description: "Slim fit, notch lapel, fully lined — office to evening ready.",
    price: 159.99,
    comparePrice: 199.99,
    brand: "Style Avenue",
    stock: 25,
    categorySlug: "men",
    vendorKey: "fashion",
    isFeatured: true,
    rating: 4.4,
    reviewCount: 38,
    location: "Boston, USA",
    image: IMG.blazer,
  },
  {
    name: "Polarized Aviator Sunglasses",
    slug: "polarized-aviator-sunglasses",
    description: "UV400 protection, metal frame, includes hard case.",
    price: 34.99,
    comparePrice: 49.99,
    brand: "Style Avenue",
    stock: 200,
    categorySlug: "fashion-accessories",
    vendorKey: "fashion",
    rating: 4.3,
    reviewCount: 178,
    location: "Miami, USA",
    image: IMG.sunglasses,
  },
  // Home
  {
    name: "Modern L-Shaped Sectional Sofa",
    slug: "modern-l-shaped-sectional-sofa",
    description: "Plush cushions, reversible chaise, seats up to five comfortably.",
    price: 899.99,
    comparePrice: 1199.99,
    brand: "Home Comfort Co.",
    stock: 8,
    categorySlug: "home-furniture",
    vendorKey: "home",
    isFeatured: true,
    rating: 4.6,
    reviewCount: 34,
    location: "Denver, USA",
    image: IMG.sofa,
  },
  {
    name: "Smart LED Desk Lamp",
    slug: "smart-led-desk-lamp",
    description: "Adjustable brightness and color temperature, USB charging port.",
    price: 39.99,
    brand: "Home Comfort Co.",
    stock: 85,
    categorySlug: "home-kitchen",
    vendorKey: "home",
    rating: 4.4,
    reviewCount: 127,
    location: "Phoenix, USA",
    image: IMG.lamp,
  },
  {
    name: "10-Piece Non-Stick Cookware Set",
    slug: "10-piece-nonstick-cookware-set",
    description: "Induction compatible, dishwasher safe, includes lids and utensils.",
    price: 149.99,
    comparePrice: 199.99,
    brand: "Home Comfort Co.",
    stock: 42,
    categorySlug: "home-kitchen",
    vendorKey: "home",
    rating: 4.5,
    reviewCount: 89,
    location: "Atlanta, USA",
    image: IMG.cookware,
  },
  // Sports
  {
    name: "Extra Thick Yoga Mat Pro",
    slug: "extra-thick-yoga-mat-pro",
    description: "6mm non-slip surface, carrying strap included, eco-friendly TPE.",
    price: 34.99,
    brand: "RunFast",
    stock: 140,
    categorySlug: "fitness",
    vendorKey: "fashion",
    rating: 4.6,
    reviewCount: 245,
    location: "Oregon, USA",
    image: IMG.yoga,
  },
  {
    name: "4-Person Camping Tent",
    slug: "4-person-camping-tent",
    description: "Waterproof rainfly, easy setup, two vestibules for gear storage.",
    price: 189.99,
    comparePrice: 249.99,
    brand: "RunFast",
    stock: 30,
    categorySlug: "outdoor",
    vendorKey: "fashion",
    rating: 4.5,
    reviewCount: 67,
    location: "Colorado, USA",
    image: IMG.tent,
  },
  {
    name: "Adjustable Dumbbell Set 24kg",
    slug: "adjustable-dumbbell-set-24kg",
    description: "Quick-change weight plates, compact design for home gyms.",
    price: 249.99,
    brand: "RunFast",
    stock: 20,
    categorySlug: "fitness",
    vendorKey: "fashion",
    isFeatured: true,
    rating: 4.7,
    reviewCount: 52,
    location: "Texas, USA",
    image: IMG.dumbbell,
  },
  // Beauty
  {
    name: "Vitamin C Brightening Serum",
    slug: "vitamin-c-brightening-serum",
    description: "15% vitamin C, hyaluronic acid, reduces dark spots in 4 weeks.",
    price: 28.99,
    brand: "GlowLab",
    stock: 200,
    categorySlug: "skincare",
    vendorKey: "fashion",
    rating: 4.8,
    reviewCount: 412,
    location: "Los Angeles, USA",
    image: IMG.serum,
  },
  {
    name: "Matte Liquid Lipstick Trio",
    slug: "matte-liquid-lipstick-trio",
    description: "Long-wear, smudge-proof formula in three bestselling shades.",
    price: 32.99,
    comparePrice: 45.99,
    brand: "GlowLab",
    stock: 95,
    categorySlug: "makeup",
    vendorKey: "fashion",
    rating: 4.5,
    reviewCount: 189,
    location: "New York, USA",
    image: IMG.lipstick2,
  },
  // Electronics extras
  {
    name: "MagSafe Silicone Phone Case",
    slug: "magsafe-silicone-phone-case",
    description: "Shock-absorbing edges, MagSafe compatible, slim profile.",
    price: 29.99,
    brand: "TechHub",
    stock: 300,
    categorySlug: "phones",
    vendorKey: "tech",
    rating: 4.3,
    reviewCount: 567,
    location: "California, USA",
    image: IMG.phone,
  },
  {
    name: "USB-C 7-in-1 Hub",
    slug: "usb-c-7-in-1-hub",
    description: "HDMI, USB 3.0, SD card reader, and 100W pass-through charging.",
    price: 49.99,
    comparePrice: 69.99,
    brand: "TechHub",
    stock: 75,
    categorySlug: "laptops",
    vendorKey: "tech",
    rating: 4.4,
    reviewCount: 134,
    location: "Texas, USA",
    image: IMG.hub,
  },
  {
    name: "True Wireless Earbuds Pro",
    slug: "true-wireless-earbuds-pro",
    description: "ANC, transparency mode, 28-hour total battery with charging case.",
    price: 79.99,
    comparePrice: 99.99,
    brand: "SoundMax",
    stock: 160,
    categorySlug: "audio",
    vendorKey: "tech",
    isFeatured: true,
    rating: 4.6,
    reviewCount: 892,
    location: "Florida, USA",
    image: IMG.earbuds,
  },
  // Books & toys
  {
    name: "Bestseller Fiction 3-Book Bundle",
    slug: "bestseller-fiction-3-book-bundle",
    description: "Curated modern fiction set — perfect gift for avid readers.",
    price: 39.99,
    brand: "PageTurner",
    stock: 80,
    categorySlug: "books",
    vendorKey: "home",
    rating: 4.7,
    reviewCount: 56,
    location: "Boston, USA",
    image: IMG.books,
  },
  {
    name: "STEM Building Blocks 500pc",
    slug: "stem-building-blocks-500pc",
    description: "Creative construction set for ages 6+, includes storage box.",
    price: 44.99,
    brand: "PlayCraft",
    stock: 65,
    categorySlug: "toys",
    vendorKey: "home",
    rating: 4.8,
    reviewCount: 203,
    location: "Chicago, USA",
    image: IMG.toys,
  },
  {
    name: "Fighting Arcade Stick",
    slug: "fighting-arcade-stick",
    description: " Tournament-grade arcade stick for PC and console.",
    price: 149.99,
    brand: "GameZone",
    stock: 35,
    categorySlug: "gaming-accessories",
    vendorKey: "gaming",
    rating: 4.5,
    reviewCount: 88,
    location: "Seattle, USA",
    image: IMG.controller,
  },
  {
    name: "Handheld Retro Game Console",
    slug: "handheld-retro-game-console",
    description: "500 classic games built-in, 3.5-inch color screen.",
    price: 49.99,
    brand: "GameZone",
    stock: 90,
    categorySlug: "gaming-consoles",
    vendorKey: "gaming",
    rating: 4.3,
    reviewCount: 201,
    location: "Austin, USA",
    image: IMG.switchImg,
  },
  {
    name: "Women's Knit Cardigan",
    slug: "womens-knit-cardigan",
    description: "Soft knit layer for cool evenings, available in 6 colors.",
    price: 42.99,
    brand: "Style Avenue",
    stock: 55,
    categorySlug: "women",
    vendorKey: "fashion",
    rating: 4.4,
    reviewCount: 72,
    location: "Los Angeles, USA",
    image: IMG.hoodie,
  },
  {
    name: "Men's Leather Belt",
    slug: "mens-leather-belt",
    description: "Full-grain leather with brushed nickel buckle.",
    price: 34.99,
    brand: "Style Avenue",
    stock: 100,
    categorySlug: "fashion-accessories",
    vendorKey: "fashion",
    rating: 4.3,
    reviewCount: 145,
    location: "New York, USA",
    image: IMG.bag,
  },
  {
    name: "Memory Foam Throw Pillows (2-Pack)",
    slug: "memory-foam-throw-pillows",
    description: "Hypoallergenic covers, plush support for sofa or bed.",
    price: 29.99,
    brand: "Home Comfort Co.",
    stock: 110,
    categorySlug: "home-furniture",
    vendorKey: "home",
    rating: 4.5,
    reviewCount: 198,
    location: "Denver, USA",
    image: IMG.sofa,
  },
  {
    name: "Indoor Basketball",
    slug: "indoor-basketball",
    description: "Official size 7, composite leather grip.",
    price: 24.99,
    brand: "RunFast",
    stock: 75,
    categorySlug: "fitness",
    vendorKey: "fashion",
    rating: 4.2,
    reviewCount: 56,
    location: "Texas, USA",
    image: IMG.dumbbell,
  },
  {
    name: "Gentle Face Cleanser",
    slug: "gentle-face-cleanser",
    description: "Daily cleanser for all skin types, 200ml pump bottle.",
    price: 18.99,
    brand: "GlowLab",
    stock: 180,
    categorySlug: "skincare",
    vendorKey: "fashion",
    rating: 4.6,
    reviewCount: 334,
    location: "Miami, USA",
    image: IMG.serum,
  },
  {
    name: "11\" Tablet Wi-Fi 128GB",
    slug: "tablet-wifi-128gb",
    description: "Stunning display, all-day battery, perfect for streaming and work.",
    price: 449.99,
    comparePrice: 529.99,
    brand: "TechHub",
    stock: 40,
    categorySlug: "phones",
    vendorKey: "tech",
    isFeatured: true,
    rating: 4.5,
    reviewCount: 167,
    location: "California, USA",
    image: IMG.phone,
  },
  {
    name: "Science Fiction Classics Box Set",
    slug: "science-fiction-classics-box-set",
    description: "Five award-winning novels in a collectible slipcase.",
    price: 54.99,
    brand: "PageTurner",
    stock: 45,
    categorySlug: "books",
    vendorKey: "home",
    rating: 4.8,
    reviewCount: 92,
    location: "Boston, USA",
    image: IMG.books,
  },
  {
    name: "Remote Control Racing Car",
    slug: "remote-control-racing-car",
    description: "High-speed RC car with rechargeable battery and controller.",
    price: 59.99,
    brand: "PlayCraft",
    stock: 50,
    categorySlug: "toys",
    vendorKey: "home",
    rating: 4.7,
    reviewCount: 118,
    location: "Chicago, USA",
    image: IMG.toys,
  },
];

export async function seedExtendedCategories(prisma: PrismaClient) {
  const upsertChild = async (
    slug: string,
    name: string,
    parentSlug: string,
    image?: string
  ) => {
    const parent = await prisma.category.findUniqueOrThrow({
      where: { slug: parentSlug },
    });
    await prisma.category.upsert({
      where: { slug },
      update: { name, parentId: parent.id, image },
      create: { name, slug, parentId: parent.id, image },
    });
  };

  await prisma.category.upsert({
    where: { slug: "books" },
    update: {},
    create: {
      name: "Books & Media",
      slug: "books",
      image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400",
    },
  });
  await prisma.category.upsert({
    where: { slug: "toys" },
    update: {},
    create: {
      name: "Toys & Kids",
      slug: "toys",
      image: "https://images.unsplash.com/photo-1558060370-aba9b14b4237?w=400",
    },
  });

  const gaming = await prisma.category.findUniqueOrThrow({
    where: { slug: "gaming" },
  });
  await prisma.category.upsert({
    where: { slug: "gaming-accessories" },
    update: {},
    create: {
      name: "Gaming Accessories",
      slug: "gaming-accessories",
      parentId: gaming.id,
      image: IMG.controller.replace("w=800", "w=400"),
    },
  });
  await prisma.category.upsert({
    where: { slug: "gaming-consoles" },
    update: {},
    create: {
      name: "Consoles",
      slug: "gaming-consoles",
      parentId: gaming.id,
      image: IMG.console.replace("w=800", "w=400"),
    },
  });
  await prisma.category.upsert({
    where: { slug: "pc-gaming" },
    update: {},
    create: {
      name: "PC Gaming",
      slug: "pc-gaming",
      parentId: gaming.id,
      image: IMG.monitor.replace("w=800", "w=400"),
    },
  });
  await prisma.category.upsert({
    where: { slug: "video-games" },
    update: {},
    create: {
      name: "Video Games",
      slug: "video-games",
      parentId: gaming.id,
      image: IMG.gaming.replace("w=800", "w=400"),
    },
  });

  await upsertChild("fashion-accessories", "Accessories", "fashion", IMG.bag.replace("w=800", "w=400"));
  await upsertChild("fashion-shoes", "Shoes", "fashion", IMG.boots.replace("w=800", "w=400"));
  await upsertChild("home-furniture", "Furniture", "home", IMG.sofa.replace("w=800", "w=400"));
  await upsertChild("home-kitchen", "Kitchen & Décor", "home", IMG.lamp.replace("w=800", "w=400"));
  await upsertChild("fitness", "Fitness", "sports", IMG.yoga.replace("w=800", "w=400"));
  await upsertChild("outdoor", "Outdoor", "sports", IMG.tent.replace("w=800", "w=400"));
  await upsertChild("skincare", "Skincare", "beauty", IMG.serum.replace("w=800", "w=400"));
  await upsertChild("makeup", "Makeup", "beauty", IMG.lipstick2.replace("w=800", "w=400"));
}

export async function seedExtraProducts(
  prisma: PrismaClient,
  vendors: Record<"tech" | "fashion" | "gaming" | "home", string>
) {
  for (const p of EXTRA_PRODUCTS) {
    const category = await prisma.category.findUniqueOrThrow({
      where: { slug: p.categorySlug },
    });
    await prisma.product.upsert({
      where: { slug: p.slug },
      update: {
        price: p.price,
        stock: p.stock,
        isFeatured: p.isFeatured ?? false,
        comparePrice: p.comparePrice ?? null,
      },
      create: {
        name: p.name,
        slug: p.slug,
        description: p.description,
        price: p.price,
        comparePrice: p.comparePrice,
        brand: p.brand,
        stock: p.stock,
        categoryId: category.id,
        vendorId: vendors[p.vendorKey],
        isFeatured: p.isFeatured ?? false,
        rating: p.rating ?? 4.0,
        reviewCount: p.reviewCount ?? 0,
        location: p.location ?? "USA",
        images: {
          create: [{ url: p.image, sortOrder: 0 }],
        },
      },
    });
  }
}
